version: '3.8'

services:
  # FastAPI Service
  web:
    build: .
    container_name: fastapi_auth_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app # container tự cập nhật khi dùng reload
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "
      echo \"[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] [Infra] Waiting for MySQL port 3306 to be available...\";
      until exec 3<>/dev/tcp/db/3306; do
        sleep 1;
      done 2>/dev/null;
      echo \"[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] [Infra] MySQL port 3306 is open. Starting Uvicorn server...\";
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude \"app.log\"
      "

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: fastapi_auth_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}      
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"    
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: fastapi_auth_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:
  app_logs: